# Check out https://docs.codemagic.io/getting-started/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
    ios-app:
        name: iOS App
        environment:
            vars:
                XCODE_WORKSPACE: "BadBird.xcodeproj/project"
                XCODE_SCHEME: "BadBird"
            xcode: latest
            cocoapods: default
        scripts:
            - xcodebuild build -project "BadBird.xcodeproj" -scheme "BadBird" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
            - xcode-project build-ipa --project "BadBird.xcodeproj" --scheme "BadBird"
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
